config/routes.rb
Rails.application.routes.draw do
  #Manejo de gema Devise
  devise_for :users
  root 'home#index'
  get 'home/index'
  get 'home/mostrar/:id' => "home#mostrar_parametro", as: 'mostrar_parametro'
  post 'home/cambio_password_user' => "home#cambio_password_user", as: 'cambio_password_user'
  get "salir/modal_salir" => "home#modal_salir", as: "modal_salir"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "/admin", :path_names => {new: 'n', edit: 'e'} do
    resources :persona_empresa_formularios
    get "permisos/" => "persona_empresa_formularios#index_permisos", :as => "permisos"
    post "persona_empresa_formularios/consulta_permisos"
    get "/permisos/search" => "persona_empresa_formularios#search_usuario", as: "search_usuarios"
    get "/permisos/show" => "persona_empresa_formularios#mostrar_permisos", as: "mostrar_permisos"
    get "/permisos/add" => "persona_empresa_formularios#agregar_permiso", as: "agregar_permisos"
    get "/permisos/showadd" => "persona_empresa_formularios#mostrar_agregar_permisos", as: "mostrar_agregar_permisos"
    post "persona_empresa_formularios/guardar_permisos"
    get "/permisos/opc_perfil" => "persona_empresa_formularios#obtener_opciones_por_perfil", as: "obtener_opciones_por_perfil"
    get "/permisos/opc_individual" => "persona_empresa_formularios#obtener_opciones_por_individual", as: "obtener_opciones_por_individual"
    delete "/permisos/remove/:id" => "persona_empresa_formularios#eliminar_permiso", as: "eliminar_permiso"
    post 'persona_empresa_formularios/eliminar_seleccionados', to: 'persona_empresa_formularios#eliminar_seleccionados', as: :eliminar_seleccionados_componentes

    #routs datos externos
    get "/detalle/datosexterno/:dato_externo_id" => "datos_externos#index_detalle_datos_externo", as: "index_detalle_datos_externo"
    get "/nuevo/datos_externo/:id" => "datos_externos#nuevo_detalle_dato", as: "nuevo_detalle_dato"
    post "datos_externos/crea_detalle_de"

    #routs datos apis
    get "/detalle/datosapi/:datos_api_id" => "datos_apis#index_detalle_datos_api", as: "index_detalle_datos_api"
    get "/nuevo/datos_api/:id" => "datos_apis#nuevo_detalle_datos_api", as: "nuevo_detalle_datos_api"
    post "datos_apis/registro_detalle_dato_api"
    get "/editar/datos_api/:id" => "datos_apis#editar_detalle_datos_api", as: "editar_detalle_datos_api"
    post "datos_apis/actualizar_detalle_dato_api"
    get "/inactivar/datos_api/:id" => "datos_apis#inactivar_detalle_datos_api", as: "inactivar_detalle_datos_api"


    get "/empresas/search" => "usuarios#search_empresa", as: "search_empresa"
    get "/areas/search" => "usuarios#search_areas", as: "search_areas"
    get "/persona/modal_cambio_contra/:persona_id" => "personas#modal_cambiar_contrasena", as: "modal_cambiar_contrasena"
    post "personas/registrar_cambio_contrasena"
    get "/persona/registrar_token/:persona_id" => "personas#registrar_token_persona", as: "registrar_token_persona"
    get "/persona/generar_token/" => "personas#generar_token", as: "generar_token"
    get "search_area_empresa_usuario" => "usuarios#search_area_empresa_usuario", as: "search_area_empresa_usuario"

    resources :datos_apis
    resources :detalle_datos_externos
    resources :datos_externos

    #Manejo controller Usuarios
    post 'usuarios/crear_usuario'
    get 'usuarios/index'
    get 'usuarios/agregar_usuario'

    #Manejo controller Personas
    resources :personas, :path => 'pers' do
      member do
        get 'i' => "personas#inactivar", as: 'inactivar'
        get 'a' => "personas#activar", as: 'activar'
        get 'cp' => "personas#conservar_password", as: 'conservar_password'
        get 'mec' => "personas#modal_edit_email", as: 'edit_email'
        patch 'update_email' => 'personas#update_email', as: 'update_email'
        get 'reu' => "personas#remitente_email", as: 'remitente_email'
      end
    end
    get 'personas/show/:id' => "personas#show", as: 'ver_perfil'
    #get 'personas/edit/:id' => "personas#edit", as: 'edit_persona'
    patch 'personas/update'
    # get 'inactivar/:id' => "personas#inactivar", as: 'inactivar_user'
    # get 'activar/:id' => "personas#activar", as: 'activar_user'
    # get 'conservar_password/:id' => "personas#conservar_password", as: 'conservar_password_usuario'
    #resources :personas , only: [:show, :edit, :update]


    post 'home/registrar_parametro'
    post "home/registrar_area_temporal"

    #Manejo controller empresas
    resources :empresas, :path => 'empresa' do
      member do
        get 'i' => "empresas#inactivar", as: 'inactivar'
        get 'a' => "empresas#activar", as: 'activar'
      end
    end

    #Manejo controller areas
    resources :areas, :path => 'area' do
      member do
        get 'i' => "areas#inactivar", as: 'inactivar'
        get 'a' => "areas#activar", as: 'activar'
      end
    end

    #Manejo controller rol
    resources :roles, :path => 'rol' do
      member do
        get 'i' => "roles#inactivar", as: 'inactivar'
        get 'a' => "roles#activar", as: 'activar'
      end
    end

    #manejo de controller peresonas - areas
    resources :personas_areas
    get 'usuario_area/inactivar/:id' => "personas_areas#inactivar_usuario_area", as: 'inactivar_usuario_area'
    get "personas_areas/search_areas_by_empresa"

    #Manejo de controller menu
    resources :menus, :path => 'menu' do
      member do
        get 'i' => "menus#inactivar", as: 'inactivar'
        get 'a' => "menus#activar", as: 'activar'
      end
    end

    resources :sub_opciones, :path => 'sub_opcion' do
      member do
        get 'i' => "sub_opciones#inactivar", as: 'inactivar'
        get 'a' => "sub_opciones#activar", as: 'activar'
      end
    end

    #Manejo de controller Opciones
    resources :opciones, :path => 'opcion' do
      member do
        get 'i' => "opciones#inactivar", as: 'inactivar'
        get 'a' => "opciones#activar", as: 'activar'
      end
    end

    #Manejo de controller menu por rol
    resources :menu_roles, :path => 'menu_rol' do
      member do
        get 'i' => "menu_roles#inactivar", as: 'inactivar'
        get 'a' => "menu_roles#activar", as: 'activar'
      end
    end

    #Manejo de controller atributo
    resources :atributos
    get 'atributo/inactivar/:id' => "atributos#inactivar_atributo", as: 'inactivar_atributo'

    #Manejo de controller componente
    resources :componentes
    get 'componente/inactivar/:id' => "componentes#inactivar_componente", as: 'inactivar_componente'

    #Manejo de controller opcion componentes - atributos
    resources :opcion_cas
    get 'opcion_ca/inactivar/:id' => "opcion_cas#inactivar_opcion_ca", as: 'inactivar_opcion_ca'

    #Manejo de controller persona, empresa, formularios
    get 'personas/search/' => "persona_empresa_formularios#search", as: 'search'

    #Para buscar las areas por empresa por persona de un usuario
    get '/permisos/searchemp/' => "persona_empresa_formularios#search_areas_persona", as: 'searchemp'
  end

  scope "/catalogos", :path_names => {new: 'n', edit: 'e'} do
    resources :unidad_medidas, :path => 'unidad_medida' do
      collection do
        get 'search_empresa', to: 'unidad_medidas#search_empresa', as: 'search_empresa'
        get 'search_datos', to: 'unidad_medidas#search_datos', as: 'search_datos'
      end

      member do
        get 'i' => "unidad_medidas#inactivar", as: 'inactivar'
        get 'a' => "unidad_medidas#activar", as: 'activar'
      end
    end

    resources :tipo_selecciones, :path => 'tipo_seleccion' do
      member do
        get 'i' => "tipo_selecciones#inactivar", as: 'inactivar'
        get 'a' => "tipo_selecciones#activar", as: 'activar'
      end
    end

    resources :tipo_contenidos, :path => 'tipo_contenido' do
      member do
        get 'i' => "tipo_contenidos#inactivar", as: 'inactivar'
        get 'a' => "tipo_contenidos#activar", as: 'activar'
      end
    end

    resources :tipo_campos, :path => 'tipo_campo' do
      member do
        get 'i' => "tipo_campos#inactivar", as: 'inactivar'
        get 'a' => "tipo_campos#activar", as: 'activar'
      end
    end

    resources :tipo_formularios, :path => 'tipo_form' do
      collection do
        get 'search_empresa', to: 'tipo_formularios#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "tipo_formularios#inactivar", as: 'inactivar'
        get 'a' => "tipo_formularios#activar", as: 'activar'
      end
    end

    resources :tipo_frecuencias, :path => 'tipo_frec' do
      collection do
        get 'search_empresa', to: 'tipo_frecuencias#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "tipo_frecuencias#inactivar", as: 'inactivar'
        get 'a' => "tipo_frecuencias#activar", as: 'activar'
      end
    end
  end

  scope "/configuraciones", :path_names => {new: 'n', edit: 'e'} do
    resources :config_sub_preguntas, :path => 'cfg_sub_preg' do
      collection do
        get 'search_empresa', to: 'config_sub_preguntas#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "config_sub_preguntas#inactivar", as: 'inactivar'
        get 'a' => "config_sub_preguntas#activar", as: 'activar'
      end
    end

    resources :config_preguntas, :path => 'cfg_preg' do
      collection do
        get 'search_empresa', to: 'config_preguntas#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "config_preguntas#inactivar", as: 'inactivar'
        get 'a' => "config_preguntas#activar", as: 'activar'
      end
    end

    resources :config_formularios, :path => 'cfg_form' do
      collection do
        get 'search_empresa', to: 'config_formularios#search_empresa', as: 'search_empresa'
        get 'search_area', to: 'config_formularios#search_area', as: 'search_area'
        get 'search_tipo_form', to: 'config_formularios#search_tipo_form', as: 'search_tipo_form'

app/models/datos_api.rb
# == Schema Information
#
# Table name: datos_apis
#
#  id              :integer          not null, primary key
#  nombre          :string(255)
#  url_api         :string(255)
#  token           :string(255)
#  estado          :string(255)
#  user_created_id :integer
#  user_updated_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class DatosApi < ApplicationRecord
  has_many :detalle_datos_apis 
  def destroy
    update_attribute(:estado, 'I')
    self.detalle_datos_apis.update_all("estado = 'I'")
  end
end

app/controllers/datos_apis_controller.rb
class DatosApisController < ApplicationController
  before_action :set_datos_api, only: %i[ show edit update destroy ]
  before_action :comprobar_permiso

  # GET /datos_apis or /datos_apis.json
  def index
    @datos_apis = DatosApi.where('estado = ?', 'A')
  end

  # GET /datos_apis/1 or /datos_apis/1.json
  def show
  end

  # GET /datos_apis/new
  def new
    @datos_api = DatosApi.new
  end

  # GET /datos_apis/1/edit
  def edit
  end

  # POST /datos_apis or /datos_apis.json
  def create
    @datos_api = DatosApi.new(datos_api_params)
    @datos_api.estado = 'A'
    @datos_api.user_created_id = current_user.id

    respond_to do |format|
      if @datos_api.save
        format.html { redirect_to datos_apis_path, notice: "Dato de API creado exitosamente." }
        format.json { render :show, status: :created, location: @datos_api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @datos_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos_apis/1 or /datos_apis/1.json
  def update
    respond_to do |format|
      @datos_api.user_updated_id = current_user.id
      if @datos_api.update(datos_api_params)
        format.html { redirect_to datos_api_url(@datos_api), notice: "Datos API actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @datos_api }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @datos_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos_apis/1 or /datos_apis/1.json
  def destroy
    @datos_api.destroy

    respond_to do |format|
      format.html { redirect_to datos_apis_url, notice: "Datos API inactivado exitosamente." }
      format.json { head :no_content }
    end
  end

  def index_detalle_datos_api
    datos_api_id = params[:datos_api_id]
    @datos_api = DatosApi.find(datos_api_id)
    @detalle_datos_api = DetalleDatosApi.where('estado =? and datos_api_id =?', 'A', datos_api_id )
  end 

  def nuevo_detalle_datos_api
    datos_api_id = params[:id]
    @datos_api = DatosApi.find(datos_api_id)
  end 

  def registro_detalle_dato_api
    @detalle_datos_api = DetalleDatosApi.new(detalle_datos_api_params)
    @detalle_datos_api.estado = 'A'
    @detalle_datos_api.user_created_id = current_user.id

    respond_to do |format|
      if @detalle_datos_api.save
        format.html { redirect_to index_detalle_datos_api_path(:datos_api_id => params[:nuevo_detalle_dato_api][:datos_api_id]), notice: "Detalle de API creado exitosamente." }
        format.json { render :show, status: :created, location: @detalle_datos_api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalle_datos_api.errors, status: :unprocessable_entity }
      end
    end
  end 

  def editar_detalle_datos_api
    detalle_datos_api_id = params[:id]
    @detalle_datos_api = DetalleDatosApi.find(detalle_datos_api_id)


  end 

  def actualizar_detalle_dato_api

    @detalle_dato_api = DetalleDatosApi.find(params[:editar_detalle_dato_api][:datos_api_id])
    @detalle_dato_api.nombre = params[:editar_detalle_dato_api][:nombre]
    @detalle_dato_api.param1 = params[:editar_detalle_dato_api][:param1]
    @detalle_dato_api.param2 = params[:editar_detalle_dato_api][:param2]
    @detalle_dato_api.param3 = params[:editar_detalle_dato_api][:param3] 
    @detalle_dato_api.param4 = params[:editar_detalle_dato_api][:param4]
    @detalle_dato_api.param5 = params[:editar_detalle_dato_api][:param5]
    @detalle_dato_api.tipo = params[:editar_detalle_dato_api][:tipo]
    @detalle_dato_api.body = params[:editar_detalle_dato_api][:body]
    @detalle_dato_api.user_updated_id = current_user.id

    respond_to do |format|
      if @detalle_dato_api.save
        format.html { redirect_to index_detalle_datos_api_path(:datos_api_id => params[:editar_detalle_dato_api][:datos_api_id]), notice: "Detalle de API actualizado exitosamente." }
        format.json { render :show, status: :created, location: @detalle_dato_api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalle_dato_api.errors, status: :unprocessable_entity }
      end
    end 
  end
  
  def inactivar_detalle_datos_api
    detalle_datos_api_id = params[:id]
    @detalle_dato_api = DetalleDatosApi.find(detalle_datos_api_id)

    @detalle_dato_api.estado = 'I'
    @detalle_dato_api.user_updated_id = current_user.id

    respond_to do |format|
      if @detalle_dato_api.save
        format.html { redirect_to index_detalle_datos_api_path(:datos_api_id => @detalle_dato_api.datos_api_id), notice: "Detalle de API inactivado exitosamente." }
        format.json { render :show, status: :created, location: @detalle_dato_api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalle_dato_api.errors, status: :unprocessable_entity }
      end
    end 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datos_api
      @datos_api = DatosApi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datos_api_params
      params.require(:datos_api).permit(:nombre, :url_api, :token, :estado, :user_created_id, :user_updated_id)
    end

    def detalle_datos_api_params
      params.require(:nuevo_detalle_dato_api).permit(:datos_api_id, :nombre, :param1, :param2, :param3, :param4, :param5, :tipo, :body)
    end

    def editar_detalle_datos_api_params
      params.require(:editar_detalle_dato_api).permit(:datos_api_id, :nombre, :param1, :param2, :param3, :param4, :param5, :tipo, :body)
    end
end

app/helpers/datos_apis_helper.rb
module DatosApisHelper
end

app/views/datos_apis/_form.html.erb
<!-- Inicio datos API  -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Gestión de Datos de API</h6>
  </div>
  <div class="card-body">

    <div class="container-fluid">
      <div class="row">

        <div class="col-md-12">
          
          <%= simple_form_for(@datos_api) do |f| %>
            <div class="row">
              <div class="col-md-4">
              </div>
              <div class="col-md-4">

                <%= f.error_notification %>
                <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

                <div class="form-inputs">
                  <%= f.input :nombre, required: true, label: "Nombre", autofocus: true %>
                  <%= f.input :url_api, required: true, label: "URL API" %>
                  <%= f.input :token, label: "Token" %>
                </div>

              </div>
              <div class="col-md-4">
              </div>
            </div>
            <br />
            <div class="row">
              <div class="col-md-12 text-right">
            <% if tiene_permiso("BOTON REGISTRAR", "VER") %>    
              <%= button_tag f.submit, class: "btn btn-success btn-sm" do %>
              <span class="icon text-50">
                <i class="fas fa-edit"></i>
              </span>
              <span class="text">REGISTRAR</span>
              <%end%>
            <%end%>
              

                <%= link_to datos_apis_path, class: "btn btn-outline-danger btn-sm" do %>
                <span class="icon text-red-50">
                  <i class="fas fa-arrow-circle-left"></i>
                </span>
                <span class="text">CANCELAR</span>
                <%end%>

              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/datos_apis/edit.html.erb
<%= render 'form', datos_api: @datos_api %>

app/views/datos_apis/index.html.erb
<!-- Inicio datos externos -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Gestión de Datos Externos</h6>
    </div>
    <div class="card-body">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12 text-right">
                          <% if tiene_permiso("BOTON NUEVO REGISTRO", "VER") %>
                            <%= link_to new_datos_api_path, class: "btn btn-success btn-sm" do %>
                            <span class="icon text-white-50">
                                <i class="fas fa-plus-circle"></i>
                            </span>
                            <span class="text">AGREGAR</span>
                            <%end%>
                          <%end%>
                      
                            <%= link_to root_path, class: "btn btn-outline-danger btn-sm" do %>
                            <span class="icon text-red-50">
                                <i class="fas fa-home"></i>
                            </span>
                            <span class="text">INICIO</span>
                            <%end%>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <br />
                            <div class="col-md-12 table-responsive">
                                <table id="datatable" class="table table-hover table-sm table-bordered text-center">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>id </th>
                                            <th>Nombre</th>
                                            <th>Url API</th>
                                            <th>Token</th>
                                            <th>Estado</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <% @datos_apis.each do |datos_api| %>
                                        <tr>
                                            <td> <%= datos_api.id %> </td>
                                            <td><%= datos_api.nombre %></td>
                                            <td><%= datos_api.url_api %></td>
                                            <td><%= datos_api.token %></td>
                                            <td><%= datos_api.estado %></td>

                                            <td>
                                              <% if tiene_permiso("BOTON DETALLE", "VER") %>
                                                <%= link_to index_detalle_datos_api_path(:datos_api_id => datos_api.id), class: "btn btn-outline-success btn-sm", :"data-toggle" => "popover", :"data-content" => "Detalle API", :"data-trigger" => "hover", :"data-placement" => "top"   do %>
                                                 <i class="fas fa-list-alt"></i>
                                                <%end%>
                                              <%end%>
                                            </td>
                                            <td>
                                              <% if tiene_permiso("BOTON EDITAR REGISTRO", "VER") %>
                                                <%= link_to edit_datos_externo_path(datos_api), class: "btn btn-outline-info btn-sm " do %>
                                                <i class="fas fa-edit"></i>
                                                <%end%>
                                              <%end%>
                                             <% if tiene_permiso("BOTON ELIMINAR REGISTRO", "VER") %>
                                                <%= link_to datos_api, method: :delete, class: "btn btn-outline-danger btn-sm ", data: { confirm: 'Se eliminara' } do %>
                                                <i class="fas fa-trash-alt"></i>
                                                <%end%>
                                              <%end%>
                                          
                                            </td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/datos_apis/index_detalle_datos_api.html.erb
<!-- Inicio detalle datos API -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Detalles de Datos Externos</h6>
  </div>
  <div class="card-body">

    <div class="container-fluid">
      <div class="row">
      <div class="col-12">
          <div class="col-12 text-center">
            <h5><strong>Encabezado Datos de API</strong></h5>
          </div>
          <div class="row" style="background-color: #FDFBF0; padding: 20px; border-radius: 5px">
            <div class="col-md-12 text-right" style="color: red">
              <span class="badge badge-default">
                <h6><strong>ID: <%= @datos_api.id %></strong></h6>
              </span>
            </div>
            <div class="col-4">
              <div class="form-group">
                <label for="nombreTransaccion">Nombre</label>
                <input type="text" class="form-control" id="nombreLabor" value="<%= @datos_api.nombre%>" disabled>
              </div>
            </div>
            <div class="col-8">
              <div class="form-group">
                <label for="nombreTransaccion">URL</label>
                <input type="text" class="form-control" id="nombreLabor" value="<%= @datos_api.url_api%>" disabled>
              </div>
            </div>
          </div>
          <br>
        </div>
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12 text-right">
            
              <%= link_to nuevo_detalle_datos_api_path(:id => @datos_api.id), class: "btn btn-success btn-sm" do %>
              <span class="icon text-50">
                <i class="fas fa-plus-circle"></i>
              </span>
              <span class="text">AGREGAR</span>
              <%end%>
           

              <%= link_to datos_apis_path, class: "btn btn-outline-danger btn-sm" do %>
              <span class="icon text-red-50">
                <i class="fas fa-arrow-circle-left"></i>
              </span>
              <span class="text">Regresar</span>
              <%end%>
            </div>

          </div>
          <div class="row">
            <div class="col-md-12">
              <br />
              <div class="col-md-12 table-responsive">
                <table id="datatable" class="table table-hover table-sm table-bordered text-center">
                  <thead class="thead-light">
                    <tr>
                      <th>Id </th>
                      <th>Datos API</th>
                      <th>Nombre</th>
                      <th>Param1</th>
                      <th>Param2</th>
                      <th>Param3</th>
                      <th>Param4</th>
                      <th>Param5</th>
                      <th>Tipo</th>
                      <th>Body</th>
                      <th>Documentación</th>
                      <th>Opciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @detalle_datos_api.each do |detalle_datos_api| %>
                    <tr>
                      <td><%= detalle_datos_api.id %> </td>
                      <td><%= detalle_datos_api.datos_api.nombre %></td>
                      <td><%= detalle_datos_api.nombre %></td>
                      <td><%= detalle_datos_api.param1 %></td>
                      <td><%= detalle_datos_api.param2 %></td>
                      <td><%= detalle_datos_api.param3 %></td>
                      <td><%= detalle_datos_api.param4 %></td>
                      <td><%= detalle_datos_api.param5 %></td>
                      <td><%= detalle_datos_api.tipo %></td>
                      <td><%= detalle_datos_api.body %></td>
                      <td>
                          <%= link_to documentacion_pdf_path(:api_id => detalle_datos_api.id, :nombre => detalle_datos_api.nombre), target: :_blank, class: "btn btn-outline-warning btn-sm" do %>
                           <i class="fas fa-file-signature"></i>
                          <%end%>
                      </td>

                      <td>
                      
                        <%= link_to editar_detalle_datos_api_path(:id => detalle_datos_api.id), class: "btn btn-outline-info btn-sm " do %>
                        <i class="fas fa-edit"></i>
                        <%end%>
                                         
                        <%= link_to  inactivar_detalle_datos_api_path(:id => detalle_datos_api.id), class: "btn btn-outline-danger btn-sm ", data: { confirm: 'Se eliminara' } do %>
                        <i class="fas fa-trash-alt"></i>
                        <%end%>
                    
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/datos_apis/new.html.erb
<%= render 'form', datos_api: @datos_api %>

app/views/datos_apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @datos_api.nombre %>
</p>

<p>
  <strong>Url api:</strong>
  <%= @datos_api.url_api %>
</p>

<p>
  <strong>Token:</strong>
  <%= @datos_api.token %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @datos_api.estado %>
</p>

<p>
  <strong>User created:</strong>
  <%= @datos_api.user_created_id %>
</p>

<p>
  <strong>User update:</strong>
  <%= @datos_api.user_updated_id %>
</p>

<%= link_to 'Edit', edit_datos_api_path(@datos_api) %> |
<%= link_to 'Back', datos_apis_path %>