config/routes.rb
Rails.application.routes.draw do
  #Manejo de gema Devise
  devise_for :users
  root 'home#index'
  get 'home/index'
  get 'home/mostrar/:id' => "home#mostrar_parametro", as: 'mostrar_parametro'
  post 'home/cambio_password_user' => "home#cambio_password_user", as: 'cambio_password_user'
  get "salir/modal_salir" => "home#modal_salir", as: "modal_salir"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "/admin", :path_names => {new: 'n', edit: 'e'} do
    resources :persona_empresa_formularios
    get "permisos/" => "persona_empresa_formularios#index_permisos", :as => "permisos"
    post "persona_empresa_formularios/consulta_permisos"
    get "/permisos/search" => "persona_empresa_formularios#search_usuario", as: "search_usuarios"
    get "/permisos/show" => "persona_empresa_formularios#mostrar_permisos", as: "mostrar_permisos"
    get "/permisos/add" => "persona_empresa_formularios#agregar_permiso", as: "agregar_permisos"
    get "/permisos/showadd" => "persona_empresa_formularios#mostrar_agregar_permisos", as: "mostrar_agregar_permisos"
    post "persona_empresa_formularios/guardar_permisos"
    get "/permisos/opc_perfil" => "persona_empresa_formularios#obtener_opciones_por_perfil", as: "obtener_opciones_por_perfil"
    get "/permisos/opc_individual" => "persona_empresa_formularios#obtener_opciones_por_individual", as: "obtener_opciones_por_individual"
    delete "/permisos/remove/:id" => "persona_empresa_formularios#eliminar_permiso", as: "eliminar_permiso"
    post 'persona_empresa_formularios/eliminar_seleccionados', to: 'persona_empresa_formularios#eliminar_seleccionados', as: :eliminar_seleccionados_componentes

    #routs datos externos
    get "/detalle/datosexterno/:dato_externo_id" => "datos_externos#index_detalle_datos_externo", as: "index_detalle_datos_externo"
    get "/nuevo/datos_externo/:id" => "datos_externos#nuevo_detalle_dato", as: "nuevo_detalle_dato"
    post "datos_externos/crea_detalle_de"

    #routs datos apis
    get "/detalle/datosapi/:datos_api_id" => "datos_apis#index_detalle_datos_api", as: "index_detalle_datos_api"
    get "/nuevo/datos_api/:id" => "datos_apis#nuevo_detalle_datos_api", as: "nuevo_detalle_datos_api"
    post "datos_apis/registro_detalle_dato_api"
    get "/editar/datos_api/:id" => "datos_apis#editar_detalle_datos_api", as: "editar_detalle_datos_api"
    post "datos_apis/actualizar_detalle_dato_api"
    get "/inactivar/datos_api/:id" => "datos_apis#inactivar_detalle_datos_api", as: "inactivar_detalle_datos_api"


    get "/empresas/search" => "usuarios#search_empresa", as: "search_empresa"
    get "/areas/search" => "usuarios#search_areas", as: "search_areas"
    get "/persona/modal_cambio_contra/:persona_id" => "personas#modal_cambiar_contrasena", as: "modal_cambiar_contrasena"
    post "personas/registrar_cambio_contrasena"
    get "/persona/registrar_token/:persona_id" => "personas#registrar_token_persona", as: "registrar_token_persona"
    get "/persona/generar_token/" => "personas#generar_token", as: "generar_token"
    get "search_area_empresa_usuario" => "usuarios#search_area_empresa_usuario", as: "search_area_empresa_usuario"

    resources :datos_apis
    resources :detalle_datos_externos
    resources :datos_externos

    #Manejo controller Usuarios
    post 'usuarios/crear_usuario'
    get 'usuarios/index'
    get 'usuarios/agregar_usuario'

    #Manejo controller Personas
    resources :personas, :path => 'pers' do
      member do
        get 'i' => "personas#inactivar", as: 'inactivar'
        get 'a' => "personas#activar", as: 'activar'
        get 'cp' => "personas#conservar_password", as: 'conservar_password'
        get 'mec' => "personas#modal_edit_email", as: 'edit_email'
        patch 'update_email' => 'personas#update_email', as: 'update_email'
        get 'reu' => "personas#remitente_email", as: 'remitente_email'
      end
    end
    get 'personas/show/:id' => "personas#show", as: 'ver_perfil'
    #get 'personas/edit/:id' => "personas#edit", as: 'edit_persona'
    patch 'personas/update'
    # get 'inactivar/:id' => "personas#inactivar", as: 'inactivar_user'
    # get 'activar/:id' => "personas#activar", as: 'activar_user'
    # get 'conservar_password/:id' => "personas#conservar_password", as: 'conservar_password_usuario'
    #resources :personas , only: [:show, :edit, :update]


    post 'home/registrar_parametro'
    post "home/registrar_area_temporal"

    #Manejo controller empresas
    resources :empresas, :path => 'empresa' do
      member do
        get 'i' => "empresas#inactivar", as: 'inactivar'
        get 'a' => "empresas#activar", as: 'activar'
      end
    end

    #Manejo controller areas
    resources :areas, :path => 'area' do
      member do
        get 'i' => "areas#inactivar", as: 'inactivar'
        get 'a' => "areas#activar", as: 'activar'
      end
    end

    #Manejo controller rol
    resources :roles, :path => 'rol' do
      member do
        get 'i' => "roles#inactivar", as: 'inactivar'
        get 'a' => "roles#activar", as: 'activar'
      end
    end

    #manejo de controller peresonas - areas
    resources :personas_areas
    get 'usuario_area/inactivar/:id' => "personas_areas#inactivar_usuario_area", as: 'inactivar_usuario_area'
    get "personas_areas/search_areas_by_empresa"

    #Manejo de controller menu
    resources :menus, :path => 'menu' do
      member do
        get 'i' => "menus#inactivar", as: 'inactivar'
        get 'a' => "menus#activar", as: 'activar'
      end
    end

    resources :sub_opciones, :path => 'sub_opcion' do
      member do
        get 'i' => "sub_opciones#inactivar", as: 'inactivar'
        get 'a' => "sub_opciones#activar", as: 'activar'
      end
    end

    #Manejo de controller Opciones
    resources :opciones, :path => 'opcion' do
      member do
        get 'i' => "opciones#inactivar", as: 'inactivar'
        get 'a' => "opciones#activar", as: 'activar'
      end
    end

    #Manejo de controller menu por rol
    resources :menu_roles, :path => 'menu_rol' do
      member do
        get 'i' => "menu_roles#inactivar", as: 'inactivar'
        get 'a' => "menu_roles#activar", as: 'activar'
      end
    end

    #Manejo de controller atributo
    resources :atributos
    get 'atributo/inactivar/:id' => "atributos#inactivar_atributo", as: 'inactivar_atributo'

    #Manejo de controller componente
    resources :componentes
    get 'componente/inactivar/:id' => "componentes#inactivar_componente", as: 'inactivar_componente'

    #Manejo de controller opcion componentes - atributos
    resources :opcion_cas
    get 'opcion_ca/inactivar/:id' => "opcion_cas#inactivar_opcion_ca", as: 'inactivar_opcion_ca'

    #Manejo de controller persona, empresa, formularios
    get 'personas/search/' => "persona_empresa_formularios#search", as: 'search'

    #Para buscar las areas por empresa por persona de un usuario
    get '/permisos/searchemp/' => "persona_empresa_formularios#search_areas_persona", as: 'searchemp'
  end

  scope "/catalogos", :path_names => {new: 'n', edit: 'e'} do
    resources :unidad_medidas, :path => 'unidad_medida' do
      collection do
        get 'search_empresa', to: 'unidad_medidas#search_empresa', as: 'search_empresa'
        get 'search_datos', to: 'unidad_medidas#search_datos', as: 'search_datos'
      end

      member do
        get 'i' => "unidad_medidas#inactivar", as: 'inactivar'
        get 'a' => "unidad_medidas#activar", as: 'activar'
      end
    end

    resources :tipo_selecciones, :path => 'tipo_seleccion' do
      member do
        get 'i' => "tipo_selecciones#inactivar", as: 'inactivar'
        get 'a' => "tipo_selecciones#activar", as: 'activar'
      end
    end

    resources :tipo_contenidos, :path => 'tipo_contenido' do
      member do
        get 'i' => "tipo_contenidos#inactivar", as: 'inactivar'
        get 'a' => "tipo_contenidos#activar", as: 'activar'
      end
    end

    resources :tipo_campos, :path => 'tipo_campo' do
      member do
        get 'i' => "tipo_campos#inactivar", as: 'inactivar'
        get 'a' => "tipo_campos#activar", as: 'activar'
      end
    end

    resources :tipo_formularios, :path => 'tipo_form' do
      collection do
        get 'search_empresa', to: 'tipo_formularios#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "tipo_formularios#inactivar", as: 'inactivar'
        get 'a' => "tipo_formularios#activar", as: 'activar'
      end
    end

    resources :tipo_frecuencias, :path => 'tipo_frec' do
      collection do
        get 'search_empresa', to: 'tipo_frecuencias#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "tipo_frecuencias#inactivar", as: 'inactivar'
        get 'a' => "tipo_frecuencias#activar", as: 'activar'
      end
    end
  end

  scope "/configuraciones", :path_names => {new: 'n', edit: 'e'} do
    resources :config_sub_preguntas, :path => 'cfg_sub_preg' do
      collection do
        get 'search_empresa', to: 'config_sub_preguntas#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "config_sub_preguntas#inactivar", as: 'inactivar'
        get 'a' => "config_sub_preguntas#activar", as: 'activar'
      end
    end

    resources :config_preguntas, :path => 'cfg_preg' do
      collection do
        get 'search_empresa', to: 'config_preguntas#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "config_preguntas#inactivar", as: 'inactivar'
        get 'a' => "config_preguntas#activar", as: 'activar'
      end
    end

    resources :config_formularios, :path => 'cfg_form' do
      collection do
        get 'search_empresa', to: 'config_formularios#search_empresa', as: 'search_empresa'
        get 'search_area', to: 'config_formularios#search_area', as: 'search_area'
        get 'search_tipo_form', to: 'config_formularios#search_tipo_form', as: 'search_tipo_form'

app/models/tipo_formulario.rb
class TipoFormulario < ApplicationRecord
  has_many :config_formularios

  validates_presence_of :empresa_id, :area_id, :nombre, :estado, message: ": este campo es obligatorio"
  validates :estado, inclusion: { in: %w(A I), message: "%{value} no es una opción válida, Verifique!!" }
  validates :empresa_id, numericality: { only_integer: true, message: ": debe ser un número entero." }, allow_nil: true
  validates :area_id, numericality: { only_integer: true, message: ": debe ser un número entero." }, allow_nil: true
  validates :nombre, uniqueness: {case_sensitive: false, scope: [:empresa_id, :area_id, :estado], message: "El dato que intenta registrar ya existe, Verifique!!!" }

  def codigo_nombre_tipo_form
    "#{self.id} - #{self.nombre}"
  end
end

app/controllers/tipo_formularios_controller.rb
class TipoFormulariosController < ApplicationController
  include ManageStatus
  before_action :set_tipo_formulario, only: %i[ show edit update destroy ]
  before_action :comprobar_permiso

  # GET /tipo_formularios or /tipo_formularios.json
  def index
    @tipo_formularios = TipoFormulario.where(estado: ['A', 'I']).order(:id)
  end

  # GET /tipo_formularios/1 or /tipo_formularios/1.json
  def show
  end

  def search_empresa
    if params[:search_empresa_tipo_formulario_params].present?
      @parametro = params[:search_empresa_tipo_formulario_params].upcase

      @empresa = PgEmpresa.select(" id_empresa, (id_empresa||' - '||descripcion) codigo_empresa").where("id_empresa||upper(descripcion) like ?", "%#{@parametro}%").distinct
    
      respond_to do |format|
        format.json { render json: @empresa.map { |p| { valor_id: p.id_empresa, valor_text: p.codigo_empresa } } }
      end 
    elsif params[:empresa_tipo_formulario_params].present?
      @id_empresa = params[:empresa_tipo_formulario_params]
      @areas_negocio = PgArea.where(id_empresa: @id_empresa).order(id_area: :asc)
      # @unidad_medidas = PgMedida.where.not("exists(select * from unidad_medidas um where um.medida_id=pg_medida.id_medida and um.empresa_id=?)", @id_empresa).order(id_medida: :asc)

      respond_to do |format|
        format.json {
          render json: {
            list_pg_area: @areas_negocio.map { |an| { valor_id: an.id_area, valor_text: "#{an.id_area} - #{an.descripcion.upcase}" } }
          }
        }
      end
    end 
  end

  # GET /tipo_formularios/new
  def new
    @listado_empresa = PgEmpresa.where(STATUS: 'A', id_empresa: @empresa_session_area)
    @listado_area = PgArea.where(id_empresa: @empresa_session_area)
    @listado_datascope = [OpenStruct.new(id: "DATASCOPE_CHECK_LIST", valor: "DATASCOPE_CHECK_LIST"),
                          OpenStruct.new(id: "DATASCOPE_CALIDAD", valor: "DATASCOPE_CALIDAD")
                         ]
    @tipo_formulario = TipoFormulario.new
  end

  # GET /tipo_formularios/1/edit
  def edit
    @listado_empresa = PgEmpresa.where(STATUS: 'A', id_empresa: @tipo_formulario.empresa_id)
    @listado_area = PgArea.where(id_empresa: @tipo_formulario.empresa_id)
    @listado_datascope = [OpenStruct.new(id: "DATASCOPE_CHECK_LIST", valor: "DATASCOPE_CHECK_LIST"),
                          OpenStruct.new(id: "DATASCOPE_CALIDAD", valor: "DATASCOPE_CALIDAD")
                         ]
  end

  # POST /tipo_formularios or /tipo_formularios.json
  def create
    @listado_empresa = PgEmpresa.where(STATUS: 'A', id_empresa: @empresa_session_area)
    @listado_area = PgArea.where(id_empresa: @empresa_session_area)
    @listado_datascope = [OpenStruct.new(id: "DATASCOPE_CHECK_LIST", valor: "DATASCOPE_CHECK_LIST"),
                          OpenStruct.new(id: "DATASCOPE_CALIDAD", valor: "DATASCOPE_CALIDAD")
                         ]

    @tipo_formulario = TipoFormulario.new(tipo_formulario_params)
    @tipo_formulario.estado = "A"
    @tipo_formulario.user_created_id = current_user.id
    @tipo_formulario.usr_grab = set_usr_grab(current_user)

    ActiveRecord::Base.transaction do
      guardar_con_manejo_de_excepciones(@tipo_formulario, "No se pudo crear el tipo de formulario", "Error de base de datos al crear el tipo de formulario")

      respond_to do |format|
        format.html { redirect_to tipo_formularios_url, notice: "El tipo de formulario [ <strong>#{@tipo_formulario.nombre.upcase}</strong> ] se ha creado correctamente.".html_safe }
        format.json { render :show, status: :created, location: tipo_formularios_url }
      end
    end
  end

  # PATCH/PUT /tipo_formularios/1 or /tipo_formularios/1.json
  def update
    @listado_empresa = PgEmpresa.where(STATUS: 'A', id_empresa: @empresa_session_area)
    @listado_area = PgArea.where(id_empresa: @empresa_session_area)
    @listado_datascope = [OpenStruct.new(id: "DATASCOPE_CHECK_LIST", valor: "DATASCOPE_CHECK_LIST"),
                          OpenStruct.new(id: "DATASCOPE_CALIDAD", valor: "DATASCOPE_CALIDAD")
                         ]

    @tipo_formulario.user_updated_id = current_user.id
    @tipo_formulario.usr_modi = set_usr_modi(current_user)

    ActiveRecord::Base.transaction do
      actualizar_con_manejo_de_excepciones(@tipo_formulario, tipo_formulario_params, "No se pudo actualizar el tipo de formulario", "Error de base de datos al actualizar el tipo de formulario")

      respond_to do |format|
        format.html { redirect_to tipo_formularios_url, notice: "El tipo de formulario [ <strong>#{@tipo_formulario.nombre.upcase}</strong> ] se ha actualizado correctamente.".html_safe }
        format.json { render :show, status: :ok, location: tipo_formularios_url }
      end
    end
  end

  # DELETE /tipo_formularios/1 or /tipo_formularios/1.json
  def destroy
    @tipo_formulario.destroy

    respond_to do |format|
      format.html { redirect_to tipo_formularios_url, notice: "Tipo formulario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def inactivar
    change_status_to('I', TipoFormulario, params[:id], tipo_formularios_url)
  end

  def activar
    change_status_to('A', TipoFormulario, params[:id], tipo_formularios_url)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_formulario
      @tipo_formulario = TipoFormulario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_formulario_params
      params.require(:tipo_formulario).permit(TipoFormulario.attribute_names.map(&:to_sym))
    end
end

app/views/tipo_formularios/_form.html.erb
<%= simple_form_for(@tipo_formulario) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <% 
    if titulo_tipo_formulario.upcase == 'ACTUALIZAR' 
      @estado_campo = true
  %>
      <%= f.hidden_field :empresa_id, value: f.object.empresa_id %>
      <%= f.hidden_field :area_id, value: f.object.area_id %>
  <%
    else  
      @estado_campo = false
    end 
  %>

  <div class="card shadow">
    <div class="card-header py-3">
      <h5 class="m-0 font-weight-bold text-primary">Gestión Tipo de Formulario</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-12">
          <div class="form-inputs">
            <div class="row">
              <div class="col-md">
                <%= f.input :empresa_id, label: "Empresa", collection: @listado_empresa, value_method: :id_empresa, label_method: :codigo_descripcion_empresa, include_blank: "Seleccione una empresa", input_html: { class: "select2", id: 'empresa_id_tipoFormulario', 'data-endpoint': search_empresa_tipo_formularios_path, disabled: @estado_campo }, required: true %>
              </div>
              <div class="col-md">
                <%= f.input :area_id, label: "Área de Negocio", collection: @listado_area, value_method: :id_area, label_method: :codigo_descripcion_area, include_blank: "Seleccione un área de negocio", input_html: { class: "select2", id: 'area_id_tipoFormulario', disabled: @estado_campo }, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col-md">
                <%= f.input :nombre %>
              </div>
              <div class="col-md">
                <%= f.input :tipo_datascope, label: "Tipo DataScope", collection: @listado_datascope, value_method: :id, label_method: :valor, include_blank: "Seleccione el tipo DataScope", input_html: { class: "select2", id: 'datascope_tipoFormulario' }, required: true %>
              </div>
            </div>
            
            <%= f.input :descripcion, as: :text, input_html: {rows: 3} %>
          </div>
        </div>
      </div>
    </div>

    <div class="card-footer shadow bg-transparent" style="background-color: #efefef !important;">
      <div class="col-md-12 text-center">
        <%= link_to tipo_formularios_url, class: "btn btn-danger btn-sm mt-2" do %>
          <span class="icon text-red-50">
            <i class="fas fa-arrow-circle-left"></i>
          </span>
          <span class="text">CANCELAR</span>
        <% end %>
  
        <% if tiene_permiso("BOTON REGISTRAR", "VER") %>
          <%= button_tag f.submit, 
              class: "btn btn-success btn-sm mt-2 btn_event_tipo_formulario", 
              data: { evento: "#{titulo_tipo_formulario}", nombre: "#{@tipo_formulario.nombre}" } do %>
            <span class="text"><%= titulo_tipo_formulario.upcase %></span>
            <span class="icon text-green-50">
              <i class="fas fa-edit"></i>
            </span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    if ($('#empresa_id_tipoFormulario').val() == "") {
      seleccionarEmpresa('#empresa_id_tipoFormulario', <%= @empresa_session_area %>, "<%= @nombre_empresa_session_area.descripcion %>");
    }
  });
</script>

app/views/tipo_formularios/edit.html.erb
<%= render 'form', tipo_formulario: @tipo_formulario, titulo_tipo_formulario: "Actualizar" %>

app/views/tipo_formularios/index.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <div class="row">
      <div class="col-md-6 table-responsive-sm text-left mt-2">
        <h5 class="m-0 font-weight-bold text-primary">Gestión Tipos de Formulario</h5>
      </div>
      <div class="col-md-6 table-responsive-sm text-right">
        <% if tiene_permiso("BOTON NUEVO REGISTRO", "VER") %>
          <%= link_to new_tipo_formulario_path, class: "btn btn-success btn-sm mt-2" do %>
            <span class="icon text-green-50">
                <i class="fas fa-plus-circle"></i>
            </span>
            <span class="text">AGREGAR</span>
          <% end %>
        <% end %>
        <%= link_to root_path, class: "btn btn-danger btn-sm mt-2" do %>
          <span class="icon text-red-50">
              <i class="fas fa-home"></i>
          </span>
          <span class="text">INICIO</span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <div class="row">
      <div class="col-md-12 table-responsive-sm">
        <table id="datatable_tipos_formulario" class="table table-hover table-sm table-bordered display" width="100%" cellpadding="0" cellspacing="0">
          <thead class="thead-light">
            <tr>
              <th class="text-center">ID</th>
              <th>Empresa</th>
              <th>Area</th>
              <th>Nombre</th>
              <th>Descripcion</th>
              <th class="text-center">Estado</th>
              <% if tiene_permiso("BOTON EDITAR REGISTRO", "VER") %>
              <th class="text-center"></th>
              <% end %>
              <% if tiene_permiso("BOTON ELIMINAR REGISTRO", "VER") %>
              <th class="text-center"></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @tipo_formularios.each do |tf| %>
              <tr>
                <td class="text-center"><%= tf.id %></td>
                <td><%= tf.empresa_id %></td>
                <td><%= tf.area_id %></td>
                <td><%= tf.nombre %></td>
                <td><%= tf.descripcion %></td>
                <td class="text-center"><%= format_estado(tf.estado) %></td>
                <% if tiene_permiso("BOTON EDITAR REGISTRO", "VER") %>
                  <td class="text-center">
                    <% if tf.estado == "A" %>
                      <%= link_to edit_tipo_formulario_path(tf), 
                          class: "btn btn-outline-info btn-sm",
                          "data-custom-class": "popover-info", title: "ACTUALIZAR", "data-content": "#{tf.id} | #{tf.nombre.capitalize}" do %>
                        <i class="fas fa-edit"></i>
                      <% end %>
                    <% end %>
                  </td>
                <% end %>

                <% if tiene_permiso("BOTON ELIMINAR REGISTRO", "VER") %>
                  <td class="text-center">
                    <% if tf.estado == "A" %>
                      <%= link_to  inactivar_tipo_formulario_path(:id => tf.id), 
                          class: "btn btn-outline-danger btn-sm btn_status_tipo_formulario", 
                          data: { status: "Inactivar", nombre: "#{tf.id} | #{tf.nombre.capitalize}" },
                          "data-custom-class": "popover-danger", title: "INACTIVAR", "data-content": "#{tf.id} | #{tf.nombre.capitalize}" do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>
                    <% else %>
                      <%= link_to  activar_tipo_formulario_path(:id => tf.id), 
                          class: "btn btn-outline-success btn-sm btn_status_tipo_formulario", 
                          data: { status: "Activar", nombre: "#{tf.id} | #{tf.nombre.capitalize}" },
                          "data-custom-class": "popover-success", title: "ACTIVAR", "data-content": "#{tf.id} | #{tf.nombre.capitalize}" do %>
                        <i class="fas fa-trash-restore-alt"></i>
                      <% end %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/tipo_formularios/new.html.erb
<%= render 'form', tipo_formulario: @tipo_formulario, titulo_tipo_formulario: "Registrar" %>

app/views/tipo_formularios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @tipo_formulario.empresa_id %>
</p>

<p>
  <strong>Area:</strong>
  <%= @tipo_formulario.area_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_formulario.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tipo_formulario.descripcion %>
</p>

<p>
  <strong>User created:</strong>
  <%= @tipo_formulario.user_created_id %>
</p>

<p>
  <strong>User updated:</strong>
  <%= @tipo_formulario.user_updated_id %>
</p>

<p>
  <strong>Usr grab:</strong>
  <%= @tipo_formulario.usr_grab %>
</p>

<p>
  <strong>Usr modi:</strong>
  <%= @tipo_formulario.usr_modi %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @tipo_formulario.estado %>
</p>

<%= link_to 'Edit', edit_tipo_formulario_path(@tipo_formulario) %> |
<%= link_to 'Back', tipo_formularios_path %>