config/routes.rb
Rails.application.routes.draw do
  #Manejo de gema Devise
  devise_for :users
  root 'home#index'
  get 'home/index'
  get 'home/mostrar/:id' => "home#mostrar_parametro", as: 'mostrar_parametro'
  post 'home/cambio_password_user' => "home#cambio_password_user", as: 'cambio_password_user'
  get "salir/modal_salir" => "home#modal_salir", as: "modal_salir"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "/admin", :path_names => {new: 'n', edit: 'e'} do
    resources :persona_empresa_formularios
    get "permisos/" => "persona_empresa_formularios#index_permisos", :as => "permisos"
    post "persona_empresa_formularios/consulta_permisos"
    get "/permisos/search" => "persona_empresa_formularios#search_usuario", as: "search_usuarios"
    get "/permisos/show" => "persona_empresa_formularios#mostrar_permisos", as: "mostrar_permisos"
    get "/permisos/add" => "persona_empresa_formularios#agregar_permiso", as: "agregar_permisos"
    get "/permisos/showadd" => "persona_empresa_formularios#mostrar_agregar_permisos", as: "mostrar_agregar_permisos"
    post "persona_empresa_formularios/guardar_permisos"
    get "/permisos/opc_perfil" => "persona_empresa_formularios#obtener_opciones_por_perfil", as: "obtener_opciones_por_perfil"
    get "/permisos/opc_individual" => "persona_empresa_formularios#obtener_opciones_por_individual", as: "obtener_opciones_por_individual"
    delete "/permisos/remove/:id" => "persona_empresa_formularios#eliminar_permiso", as: "eliminar_permiso"
    post 'persona_empresa_formularios/eliminar_seleccionados', to: 'persona_empresa_formularios#eliminar_seleccionados', as: :eliminar_seleccionados_componentes

    #routs datos externos
    get "/detalle/datosexterno/:dato_externo_id" => "datos_externos#index_detalle_datos_externo", as: "index_detalle_datos_externo"
    get "/nuevo/datos_externo/:id" => "datos_externos#nuevo_detalle_dato", as: "nuevo_detalle_dato"
    post "datos_externos/crea_detalle_de"

    #routs datos apis
    get "/detalle/datosapi/:datos_api_id" => "datos_apis#index_detalle_datos_api", as: "index_detalle_datos_api"
    get "/nuevo/datos_api/:id" => "datos_apis#nuevo_detalle_datos_api", as: "nuevo_detalle_datos_api"
    post "datos_apis/registro_detalle_dato_api"
    get "/editar/datos_api/:id" => "datos_apis#editar_detalle_datos_api", as: "editar_detalle_datos_api"
    post "datos_apis/actualizar_detalle_dato_api"
    get "/inactivar/datos_api/:id" => "datos_apis#inactivar_detalle_datos_api", as: "inactivar_detalle_datos_api"


    get "/empresas/search" => "usuarios#search_empresa", as: "search_empresa"
    get "/areas/search" => "usuarios#search_areas", as: "search_areas"
    get "/persona/modal_cambio_contra/:persona_id" => "personas#modal_cambiar_contrasena", as: "modal_cambiar_contrasena"
    post "personas/registrar_cambio_contrasena"
    get "/persona/registrar_token/:persona_id" => "personas#registrar_token_persona", as: "registrar_token_persona"
    get "/persona/generar_token/" => "personas#generar_token", as: "generar_token"
    get "search_area_empresa_usuario" => "usuarios#search_area_empresa_usuario", as: "search_area_empresa_usuario"

    resources :datos_apis
    resources :detalle_datos_externos
    resources :datos_externos

    #Manejo controller Usuarios
    post 'usuarios/crear_usuario'
    get 'usuarios/index'
    get 'usuarios/agregar_usuario'

    #Manejo controller Personas
    resources :personas, :path => 'pers' do
      member do
        get 'i' => "personas#inactivar", as: 'inactivar'
        get 'a' => "personas#activar", as: 'activar'
        get 'cp' => "personas#conservar_password", as: 'conservar_password'
        get 'mec' => "personas#modal_edit_email", as: 'edit_email'
        patch 'update_email' => 'personas#update_email', as: 'update_email'
        get 'reu' => "personas#remitente_email", as: 'remitente_email'
      end
    end
    get 'personas/show/:id' => "personas#show", as: 'ver_perfil'
    #get 'personas/edit/:id' => "personas#edit", as: 'edit_persona'
    patch 'personas/update'
    # get 'inactivar/:id' => "personas#inactivar", as: 'inactivar_user'
    # get 'activar/:id' => "personas#activar", as: 'activar_user'
    # get 'conservar_password/:id' => "personas#conservar_password", as: 'conservar_password_usuario'
    #resources :personas , only: [:show, :edit, :update]


    post 'home/registrar_parametro'
    post "home/registrar_area_temporal"

    #Manejo controller empresas
    resources :empresas, :path => 'empresa' do
      member do
        get 'i' => "empresas#inactivar", as: 'inactivar'
        get 'a' => "empresas#activar", as: 'activar'
      end
    end

    #Manejo controller areas
    resources :areas, :path => 'area' do
      member do
        get 'i' => "areas#inactivar", as: 'inactivar'
        get 'a' => "areas#activar", as: 'activar'
      end
    end

    #Manejo controller rol
    resources :roles, :path => 'rol' do
      member do
        get 'i' => "roles#inactivar", as: 'inactivar'
        get 'a' => "roles#activar", as: 'activar'
      end
    end

    #manejo de controller peresonas - areas
    resources :personas_areas
    get 'usuario_area/inactivar/:id' => "personas_areas#inactivar_usuario_area", as: 'inactivar_usuario_area'
    get "personas_areas/search_areas_by_empresa"

    #Manejo de controller menu
    resources :menus, :path => 'menu' do
      member do
        get 'i' => "menus#inactivar", as: 'inactivar'
        get 'a' => "menus#activar", as: 'activar'
      end
    end

    resources :sub_opciones, :path => 'sub_opcion' do
      member do
        get 'i' => "sub_opciones#inactivar", as: 'inactivar'
        get 'a' => "sub_opciones#activar", as: 'activar'
      end
    end

    #Manejo de controller Opciones
    resources :opciones, :path => 'opcion' do
      member do
        get 'i' => "opciones#inactivar", as: 'inactivar'
        get 'a' => "opciones#activar", as: 'activar'
      end
    end

    #Manejo de controller menu por rol
    resources :menu_roles, :path => 'menu_rol' do
      member do
        get 'i' => "menu_roles#inactivar", as: 'inactivar'
        get 'a' => "menu_roles#activar", as: 'activar'
      end
    end

    #Manejo de controller atributo
    resources :atributos
    get 'atributo/inactivar/:id' => "atributos#inactivar_atributo", as: 'inactivar_atributo'

    #Manejo de controller componente
    resources :componentes
    get 'componente/inactivar/:id' => "componentes#inactivar_componente", as: 'inactivar_componente'

    #Manejo de controller opcion componentes - atributos
    resources :opcion_cas
    get 'opcion_ca/inactivar/:id' => "opcion_cas#inactivar_opcion_ca", as: 'inactivar_opcion_ca'

    #Manejo de controller persona, empresa, formularios
    get 'personas/search/' => "persona_empresa_formularios#search", as: 'search'

    #Para buscar las areas por empresa por persona de un usuario
    get '/permisos/searchemp/' => "persona_empresa_formularios#search_areas_persona", as: 'searchemp'
  end

  scope "/catalogos", :path_names => {new: 'n', edit: 'e'} do
    resources :unidad_medidas, :path => 'unidad_medida' do
      collection do
        get 'search_empresa', to: 'unidad_medidas#search_empresa', as: 'search_empresa'
        get 'search_datos', to: 'unidad_medidas#search_datos', as: 'search_datos'
      end

      member do
        get 'i' => "unidad_medidas#inactivar", as: 'inactivar'
        get 'a' => "unidad_medidas#activar", as: 'activar'
      end
    end

    resources :tipo_selecciones, :path => 'tipo_seleccion' do
      member do
        get 'i' => "tipo_selecciones#inactivar", as: 'inactivar'
        get 'a' => "tipo_selecciones#activar", as: 'activar'
      end
    end

    resources :tipo_contenidos, :path => 'tipo_contenido' do
      member do
        get 'i' => "tipo_contenidos#inactivar", as: 'inactivar'
        get 'a' => "tipo_contenidos#activar", as: 'activar'
      end
    end

    resources :tipo_campos, :path => 'tipo_campo' do
      member do
        get 'i' => "tipo_campos#inactivar", as: 'inactivar'
        get 'a' => "tipo_campos#activar", as: 'activar'
      end
    end

    resources :tipo_formularios, :path => 'tipo_form' do
      collection do
        get 'search_empresa', to: 'tipo_formularios#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "tipo_formularios#inactivar", as: 'inactivar'
        get 'a' => "tipo_formularios#activar", as: 'activar'
      end
    end

    resources :tipo_frecuencias, :path => 'tipo_frec' do
      collection do
        get 'search_empresa', to: 'tipo_frecuencias#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "tipo_frecuencias#inactivar", as: 'inactivar'
        get 'a' => "tipo_frecuencias#activar", as: 'activar'
      end
    end
  end

  scope "/configuraciones", :path_names => {new: 'n', edit: 'e'} do
    resources :config_sub_preguntas, :path => 'cfg_sub_preg' do
      collection do
        get 'search_empresa', to: 'config_sub_preguntas#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "config_sub_preguntas#inactivar", as: 'inactivar'
        get 'a' => "config_sub_preguntas#activar", as: 'activar'
      end
    end

    resources :config_preguntas, :path => 'cfg_preg' do
      collection do
        get 'search_empresa', to: 'config_preguntas#search_empresa', as: 'search_empresa'
      end

      member do
        get 'i' => "config_preguntas#inactivar", as: 'inactivar'
        get 'a' => "config_preguntas#activar", as: 'activar'
      end
    end

    resources :config_formularios, :path => 'cfg_form' do
      collection do
        get 'search_empresa', to: 'config_formularios#search_empresa', as: 'search_empresa'
        get 'search_area', to: 'config_formularios#search_area', as: 'search_area'
        get 'search_tipo_form', to: 'config_formularios#search_tipo_form', as: 'search_tipo_form'

app/controllers/opciones_controller.rb
class OpcionesController < ApplicationController
  include ManageStatus
  before_action :set_opcion, only: %i[ show edit update destroy ]
  before_action :comprobar_permiso

  # GET /opciones or /opciones.json
  def index
    @opciones = Opcion.where(estado: ['A', 'I'])
  end

  # GET /opciones/1 or /opciones/1.json
  def show
  end

  # GET /opciones/new
  def new
    @opcion = Opcion.new
  end

  # GET /opciones/1/edit
  def edit
  end

  # POST /opciones or /opciones.json
  def create
    @opcion = Opcion.new(opcion_params)
    @opcion.estado = "A"
    @opcion.user_created_id = current_user.id

    ActiveRecord::Base.transaction do
      guardar_con_manejo_de_excepciones(@opcion, "No se pudo crear la opción", "Error de base de datos al crear la opción")

      respond_to do |format|
        format.html { redirect_to opciones_url, notice: "La opción [ <strong>#{@opcion.nombre.upcase}</strong> ] se ha creado correctamente.".html_safe }
        format.json { render :show, status: :created, location: opciones_url }
      end
    end
  end

  # PATCH/PUT /opciones/1 or /opciones/1.json
  def update
    @opcion.user_updated_id = current_user.id

    ActiveRecord::Base.transaction do
      actualizar_con_manejo_de_excepciones(@opcion, opcion_params, "No se pudo actualizar la opción", "Error de base de datos al actualizar la opción")
      
      respond_to do |format|
        format.html { redirect_to opciones_url, notice: "La opción [ <strong>#{@opcion.nombre.upcase}</strong> ] se ha actualizado correctamente.".html_safe }
        format.json { render :show, status: :ok, location: opciones_url }
      end
    end
  end

  # DELETE /opciones/1 or /opciones/1.json
  def destroy
    @opcion.destroy
    respond_to do |format|
      format.html { redirect_to opciones_url, notice: "Opcion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

   # Inactivar opciones
  def inactivar
    change_status_to('I', Opcion, params[:id], opciones_url)
  end

  def activar
    change_status_to('A', Opcion, params[:id], opciones_url)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opcion
      @opcion = Opcion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def opcion_params
      params.require(:opcion).permit(Opcion.attribute_names.map(&:to_sym))
    end
end

app/helpers/opciones_helper.rb
module OpcionesHelper
end

app/views/opciones/_form.html.erb
<!-- Inicio Opciones -->
<div class="card shadow mb-4">
  <%= form_with(model: opcion, local: true) do |form| %>
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Gestión de Opciones por Menú</h6>
    </div>
    <div class="card-body">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-4">
              </div>
              <div class="col-md-4">
                <% if opcion.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(opcion.errors.count, "error") %> Prohibido que se guarde este item:</h2>
                    <ul>
                      <% opcion.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <br />
                <div class="field">
                  <%= form.label "Menú" %>
                  <%= form.collection_select(:menu_id, Menu.where(:estado => 'A'), :id, :nombre, {:prompt => "Seleccione un Menú"}, {:class => "form-control select2", required: true, autofocus: false}) %>
                </div>
                <br />
                <div class="field">
                  <%= form.label "Sub-Opción" %>
                  <%= form.collection_select(:sub_opcion_id, SubOpcion.where(:estado => 'A'), :id, :nombre, {:prompt => "Seleccione una Sub-Opción"}, {:class => "form-control select2", required: true, autofocus: true}) %>
                </div>
                <br>
                <div class="field">
                  <%= form.label :nombre %>
                  <%= form.text_field :nombre, class:"form-control", type: "txt", placeholder: "Ingrese solo letras", required: true, pattern: "^[A-Za-zñÑáéíóúÁÉÍÓÚ- _\s]+$" %>
                </div>
                <br />
                <div class="field">
                  <%= form.label :icono %>
                  <%= form.text_field :icono, class:"form-control", type: "txt", placeholder: "Ingrese el icono de Font Awesome", required: true %>
                </div>
                <br/>
                <div class="field mt-2 ">
                  <%= form.label :path %>
                  <%= form.text_field :path, class:"form-control", type: "txt", placeholder: "Ingrese el path de la opción", required: true %>
                </div>
                <br/>
                <div class="field mt-2">
                  <%= form.label :controlador %>
                  <%= form.text_field :controlador, class:"form-control", type: "txt", placeholder: "Ingrese controlador de opción", required: true %>
                </div>
                <br>
                <div class="field">
                  <%= form.label :componente_sidebar %>
                  <%= form.text_field :componente_sidebar, class:"form-control", type: "txt", placeholder: "Ingrese el componente para el sidebar", required: true %>
                </div>
                <br/>
                <div class="field">
                  <div class="form-check">
                    <%= form.check_box :visible_sidebar, class: 'form-check-input' %>
                    <%= form.label :visible_sidebar, class: 'form-check-label' %>
                  </div>
                </div>
                <br/>
                <div class="field">
                  <%= form.label :posicion %>
                  <%= form.text_field :posicion, class:"form-control", type: "number", placeholder: "Ingrese la posicion", required: true %>
                </div>
                <br />
                <div class="field">
                  <%= form.label :descripcion %>
                  <%= form.text_area :descripcion, size: '40x5', class:"form-control", type: "txt", placeholder: "", required: true %>
                </div>
              </div>
              <div class="col-md-4">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card-footer shadow bg-transparent" style="background-color: #efefef !important;">
      <div class="col-md-12 text-center">
        <%= link_to opciones_path, class: "btn btn-danger btn-sm mt-2" do %>
          <span class="icon text-red-50">
            <i class="fas fa-arrow-circle-left"></i>
          </span>
          <span class="text">CANCELAR</span>
        <% end %>

        <% if tiene_permiso("BOTON REGISTRAR", "VER") %>
          <%= button_tag form.submit, 
              class: "btn btn-success btn-sm mt-2 btn_event_opcion", 
              data: { evento: "#{titulo_opcion}", nombre: "#{opcion.nombre}" } do %>
            <span class="text"><%= titulo_opcion.upcase %></span>
            <span class="icon text-green-50">
              <i class="fas fa-edit"></i>
            </span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>

app/views/opciones/edit.html.erb
<%= render 'form', opcion: @opcion, titulo_opcion: "Actualizar" %>

app/views/opciones/index.html.erb
<!-- Inicio Opciones -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <div class="row">
      <div class="col-md-6 table-responsive-sm text-left mt-2">
        <h5 class="m-0 font-weight-bold text-primary">Gestión de Opciones por Menú</h5>
      </div>
      <div class="col-md-6 table-responsive-sm text-right">
        <% if tiene_permiso("BOTON NUEVO REGISTRO", "VER") %>
          <%= link_to new_opcion_path, class: "btn btn-success btn-sm mt-2" do %>
            <span class="icon text-green-50">
                <i class="fas fa-plus-circle"></i>
            </span>
            <span class="text">AGREGAR</span>
          <% end %>
        <% end %>
        <%= link_to root_path, class: "btn btn-danger btn-sm mt-2" do %>
          <span class="icon text-red-50">
              <i class="fas fa-home"></i>
          </span>
          <span class="text">INICIO</span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <div class="row">
      <div class="col-md-12 table-responsive-sm">
        <table id="datatable_opciones" class="table table-hover table-sm table-bordered display" width="100%" cellpadding="0" cellspacing="0">
          <thead class="thead-light">
            <tr>
              <th class="text-center"> id </th>
              <th> Menu</th>
              <th class="text-center"> Icono </th>
              <th> Nombre </th>
              <th> Descripción </th>
              <th> Path</th>
              <th> Controlador</th>
              <th class="text-center"> Estado</th>
              <% if tiene_permiso("BOTON EDITAR REGISTRO", "VER") %>
              <th class="text-center"></th>
              <% end %>
              <% if tiene_permiso("BOTON ELIMINAR REGISTRO", "VER") %>
              <th class="text-center"></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @opciones.each do |opcion| %>
              <tr>
                <td class="text-center"><%= opcion.id %></td>
                <td><%= opcion.menu.nombre %></td>
                <td class="text-center"><i class="<%= opcion.icono %>" aria-hidden="true"></i></td>
                <td><%= opcion.nombre %></td>
                <td><%= opcion.descripcion %></td>
                <td><%= opcion.path %></td>
                <td><%= opcion.controlador %></td>
                <td class="text-center"><%= format_estado(opcion.estado) %></td>
                <% if tiene_permiso("BOTON EDITAR REGISTRO", "VER") %>
                <td class="text-center">
                  <% if opcion.estado == "A" %>
                    <%= link_to edit_opcion_path(opcion), class: "btn btn-outline-info btn-sm " do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                  <% end %>
                </td>
                <% end %>
                
                <% if tiene_permiso("BOTON ELIMINAR REGISTRO", "VER") %>
                  <td class="text-center">
                    <% if opcion.estado == "A" %>
                      <%= link_to  inactivar_opcion_path(:id => opcion.id), 
                          class: "btn btn-outline-danger btn-sm btn_status_opcion", 
                          data: { status: "Inactivar", nombre: "#{opcion.nombre}" },
                          "data-custom-class": "popover-danger", title: "INACTIVAR", "data-content": "#{opcion.id} | #{opcion.nombre.capitalize}" do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>
                    <% else %>
                      <%= link_to  activar_opcion_path(:id => opcion.id), 
                          class: "btn btn-outline-success btn-sm btn_status_opcion", 
                          data: { status: "Activar", nombre: "#{opcion.nombre}" },
                          "data-custom-class": "popover-success", title: "ACTIVAR", "data-content": "#{opcion.id} | #{opcion.nombre.capitalize}" do %>
                        <i class="fas fa-trash-restore-alt"></i>
                      <% end %>
                    <% end %>
                  </td>
                <% end %>
                
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/opciones/new.html.erb
<%= render 'form', opcion: @opcion, titulo_opcion: "Registrar" %>

app/views/opciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @opcion.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @opcion.descripcion %>
</p>

<p>
  <strong>Icono:</strong>
  <%= @opcion.icono %>
</p>

<p>
  <strong>Path:</strong>
  <%= @opcion.path %>
</p>

<p>
  <strong>Controlador:</strong>
  <%= @opcion.controlador %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @opcion.estado %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @opcion.menu_id %>
</p>

<p>
  <strong>User create:</strong>
  <%= @opcion.user_created_id %>
</p>

<p>
  <strong>User update:</strong>
  <%= @opcion.user_updated_id %>
</p>

<%= link_to 'Edit', edit_opciones_path(@opcion) %> |
<%= link_to 'Back', opciones_index_path %>